services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ADMIN
      MONGO_INITDB_ROOT_PASSWORD: PASSWORD
    volumes:
      - ./db:/data/db
