[package]
name = "json_adder"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0"
futures = "0.3"
tokio = {version = "1.32", features = ["full"]}

[dependencies.mongodb]
version = "2.8"
features = ["tokio-runtime"]