[package]
name = "json_adder"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
futures = "0.3"
tokio = {version = "1.32", features = ["full"]}
serde_json = "1"

[dependencies.mongodb]
version = "2.8"
features = ["tokio-runtime"]