name: Rust build

on:
  push:
    branches: [ "master" ]
    paths:
      - '**.rs'
  pull_request:
    branches: [ "master" ]
    paths:
      - '**.rs'
      
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: json_adder


    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test --verbose
